### ISSUE TITLE
Vagrant not accessible

### ISSUE THREAD

**Issue by lkraider** [RocketChat/Deploy.to.Cloud#36]
```
host:$ vagrant up
(...)
==> default: [PM2][WARN] Applications rocket.chat not running, starting...
==> default: [PM2] App [rocket.chat] launched (1 instances)
==> default: ┌─────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────────────┬──────────┐
==> default: │ App name    │ id │ mode │ pid  │ status │ restart │ uptime │ memory      │ watching │
==> default: ├─────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────────────┼──────────┤
==> default: │ rocket.chat │ 0  │ fork │ 8021 │ online │ 0       │ 0s     │ 10.051 MB   │ disabled │
==> default: └─────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────────────┴──────────┘
(...)
host:$ vagrant ssh


vm:$ curl 192.168.33.10:3000
curl: (7) Failed to connect to 192.168.33.10 port 3000: Connection refused


vm:$ sudo netstat -atp tcp | grep -i "listen"
tcp        0      0 *:sunrpc                *:*                     LISTEN      526/rpcbind
tcp        0      0 localhost:28017         *:*                     LISTEN      7223/mongod
tcp        0      0 *:ssh                   *:*                     LISTEN      1630/sshd
tcp        0      0 *:51330                 *:*                     LISTEN      546/rpc.statd
tcp        0      0 localhost:27017         *:*                     LISTEN      7223/mongod
tcp6       0      0 [::]:sunrpc             [::]:*                  LISTEN      526/rpcbind
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      1630/sshd
tcp6       0      0 [::]:41441              [::]:*                  LISTEN      546/rpc.statd


vm:$ ifconfig eth1
eth1      Link encap:Ethernet  HWaddr 08:00:27:27:9a:cc
          inet addr:192.168.33.10  Bcast:192.168.33.255  Mask:255.255.255.0
```

**Comment by lkraider** [comment]
```
vm:$ tail -n 1 /var/log/rocket.chat/err.log
Meteor requires Node v0.10.40 or later.

vm:$ node --version
v0.10.25
```

**Comment by lkraider** [comment]
After updating according to [docs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions):
```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Still not working:
```
vm:$ node --version
v4.4.3

vm:$ sudo pm2 restart /var/www/rocket.chat/bundle/pm2-rocket-chat.json

vm:$ tail -n 11 /var/log/rocket.chat/err.log
Error: `/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-4.5/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/rocket.chat/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:409:26)
```

Even after trying to update/rebuild:
```
vm:$ sudo npm upgrade fibers
vm:$ sudo npm rebuild fibers

> fibers@1.0.10 install /home/vagrant/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-4.5` exists; testing
Binary is fine; exiting
fibers@1.0.10 /home/vagrant/node_modules/fibers
```

**Comment by lkraider** [comment]
Path that exists:
```
 /var/www/rocket.chat/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node
```

Path that it is looking for:
```
/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-4.5/fibers.node
```

**Comment by lkraider** [comment]
Trying to deploy with nodejs 0.12.13 the error is now:
```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/var/www/rocket.chat/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/var/www/rocket.chat/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by lkraider** [comment]
Deploying with nodejs (0.10.44-1nodesource1~trusty1) ...

Finally works!

**Comment by lkraider** [comment]
Created a pull request with my Vagrant fixes at #38
